dist: trusty
sudo: required
language: csharp
install:
- wget http://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
- sudo dpkg -i packages-microsoft-prod_1.0-1-trusty.deb
- sudo apt-get update
- sudo apt-get -y powershell
script:
- powershell -noprofile -c '"Congratulations! PowerShell is installed at $PSHOME"'
notifications:
  email: false